CREATE WAREHOUSE IF NOT EXISTS HR_ANALYTICS_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE HR_ANALYTICS_DB;

USE DATABASE HR_ANALYTICS_DB;

CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA CORE;
CREATE OR REPLACE SCHEMA MART;