USE WAREHOUSE HR_ANALYTICS_WH;
USE DATABASE HR_ANALYTICS_DB;
USE SCHEMA MART;


CREATE OR REPLACE ROLE HR_ADMIN;
CREATE OR REPLACE ROLE HR_ANALYST;

-- WAREHOUSE ACCESS
GRANT USAGE ON WAREHOUSE HR_ANALYTICS_WH TO ROLE HR_ADMIN;
GRANT USAGE ON WAREHOUSE HR_ANALYTICS_WH TO ROLE HR_ANALYST;

-- DATABASE ACCESS 

GRANT USAGE ON DATABASE HR_ANALYTICS_DB TO ROLE HR_ADMIN;
GRANT USAGE ON DATABASE HR_ANALYTICS_DB TO ROLE HR_ANALYST;

-- ADMIN 

GRANT ALL PRIVILEGES ON SCHEMA RAW TO ROLE HR_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA CORE TO ROLE HR_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA MART TO ROLE HR_ADMIN;

-- ANALYST

GRANT USAGE ON SCHEMA CORE TO ROLE HR_ANALYST;
GRANT USAGE ON SCHEMA MART TO ROLE HR_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA CORE TO ROLE HR_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA MART TO ROLE HR_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA MART TO ROLE HR_ANALYST;



--ASSIGN USER

USE SCHEMA CORE;


CREATE OR REPLACE MASKING POLICY SALARY_MASK AS 
(val DECIMAL(10,2))
RETURNS DECIMAL(10,2) ->
CASE
    WHEN CURRENT_ROLE() IN ('HR_ADMIN','ACCOUNTADMIN')
        THEN VAL
    ELSE NULL
END;


ALTER TABLE CORE.DIM_EMPLOYEE
MODIFY COLUMN SALARY
SET MASKING POLICY SALARY_MASK; 

ALTER TABLE RAW.EMPLOYEE
MODIFY COLUMN SALARY
SET MASKING POLICY SALARY_MASK;


USE ROLE ACCOUNTADMIN;
GRANT ROLE HR_ANALYST TO USER YAHYA;
GRANT ROLE HR_ADMIN TO USER YAHYA;

USE ROLE HR_ANALYST;
USE ROLE HR_ADMIN;

SELECT * FROM DIM_EMPLOYEE;
